apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-burr-iwkm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-burr-iwkm
    app.kubernetes.io/part-of: quarkus-burr
  name: quarkus-burr-iwkm
  namespace: burrzinga-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: quarkus-burr-iwkm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: quarkus-burr-iwkm
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:gTo1P-quarkus-burr-iwkm
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
