apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: quarkus-burr-iwkm
  namespace: burrzinga-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:65be42f962095a18b9a80e4c1128224f0170ff576dca402e216c67d7b14552ff
        name: my-java-quarkus
        resources: {}
status: {}
